### ISSUE TITLE
Multiple remote maps

### ISSUE THREAD

**Issue by FalsePhilosopher** [ESurge/flipperzero-firmware-unirfremix#5]
**Is your feature request related to a problem? Please describe.**
It would be cool to be able to create multiple remote maps and selectively load them up, so we can make maps for each type ie doors, gates, touchtones and load them up on the fly. I love the app but being limited to only 5 presets on the fly is kinda well limiting.

**Describe the solution you'd like**
Add some functions to be able to pick from a list of remotes you created and load it.

**Describe alternatives you've considered**
idk cry about it and go back to sifting through menus on my flipper to run multiple subs outside of my map setting?

**Additional context**
NA

**Comment by ESurge** [comment]
Thanks for the suggestion. Definitely on my list of things to work on. I may rig something up in the short term to bring more maps to the app.

This feature, plus a configuration section for button remapping and label editing is something I want to bring to this app.

I'm not a programmer by trade and coding is only a hobby for me, but I definitely am working on this.
